FROM ruby:3.2.3
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
RUN apt-get update -qq \
  && apt-get install -y ca-certificates curl gnupg \
  && apt-get update -qq \
  && apt-get install -y build-essential libpq-dev vim
RUN mkdir /oko_log
WORKDIR /oko_log
RUN gem install bundler
COPY Gemfile /oko_log/Gemfile
COPY Gemfile.lock /oko_log/Gemfile.lock
RUN bundle install
COPY . /oko_log

